### ISSUE TITLE
An example needed 

### ISSUE THREAD

**Issue by ghost** [loomchild/segment#10]
Is there an example on how to compile and run this project? thanks

**Comment by janissl** [comment]
Clone the project from this git repository. Then run maven separately in the segment and the segment-ui directories. For running, refer to readme.md.

You can also get an older compiled version from here: https://mvnrepository.com/artifact/net.loomchild/segment/2.0.0

**Comment by loomchild** [comment]
Hi. If you don't need to modify the code, you can also get binary version from Github releases: https://github.com/loomchild/segment/releases/download/2.0.0/segment-2.0.0.zip

**Comment by loomchild** [comment]
I added a little section about compiling in README, thanks guys.
