### ISSUE TITLE
java.lang.IllegalStateException: Buffer too short

### ISSUE THREAD

**Issue by matanox** [loomchild/segment#14]
I'm leaving this here till I get back around to potentially solving it.

I get this exception, few minutes into processing a cleaned up dump of the English Wikipedia.

```
java.lang.IllegalStateException: Buffer too short
	at net.loomchild.segment.srx.SrxTextIterator.next(SrxTextIterator.java:209)
	at net.loomchild.segment.ui.console.Segment.performSegment(Segment.java:604)
	at net.loomchild.segment.ui.console.Segment.createAndSegment(Segment.java:493)
	at net.loomchild.segment.ui.console.Segment.segment(Segment.java:193)
	at net.loomchild.segment.ui.console.Segment.run(Segment.java:115)
	at net.loomchild.segment.ui.console.Segment.main(Segment.java:88)

```

[Here's a pointer to the line of code](https://github.com/loomchild/segment/blob/92e64b10078726cd8bfc167144d8b43996abe42e/segment/src/main/java/net/loomchild/segment/srx/SrxTextIterator.java#L209).

It looks like this isn't really a memory issue implicated by the size of the Wikipedia dump (23GB), as on cursery browsing the code mentions working in streaming mode, and also the memory footprint seems quite constant while the program is running:

![image](https://user-images.githubusercontent.com/4996067/38132490-f3fb8374-3413-11e8-91ae-cf871b34531f.png)

But I'm not sure, maybe some parts aren't working in streaming mode (e.g. maybe the file is iterated while holding to its head). Hope to come back and possibly make a PR.

Thanks again for making this library!

**Comment by loomchild** [comment]
First of all, it's very interesting that you are using Segment on such a large corpus - thank you for providing valuable feedback.

To me it seems that the problem is that there's a segment in the text that is longer than the buffer. From README:

> Streaming version has a limitation that read buffer must be at least as long as any segment in the text.

Try increasing the buffer size via [buffer-length](https://github.com/loomchild/segment/blob/master/segment-ui/src/main/java/net/loomchild/segment/ui/console/Segment.java) option, default is 64K.

**Comment by janissl** [comment]
Such exception may occur if there is a large portion in the corpus with no sentence end punctuation marks. For such cases, my temporary solution was to write the whole buffer to the output file as is (up to the last end-of-line character and prepend the next buffer with the remainder) and move further.

**Comment by matanox** [comment]
@loomchild @janissl thanks! This makes sense. I guess in some cases, one may regard such long blobs of unpunctuated text as non-sentences. But actually they could equally include e.g. a long bulleted list without punctuation marks per item in pathological cases...

**Comment by loomchild** [comment]
Sure, quality of segmentation depends on quality of the SRX rules:) 

First of all I'd suggest increasing the buffer size to a large value and see if Segment is at least able to split the entire text, how much time it takes, etc. Only then I'd start to analyse the results, search for anomalies in segmentation and refine the rules.

Whatever you do, feel free to share the results.

**Comment by loomchild** [comment]
@matanster did you manage to resolve your issue, can I close the ticket?

**Comment by matanox** [comment]
@loomchild thanks for asking. I went around it this time, but am sure to work it out methodically on my next usage. I'd keep a note about this in the readme, as this can happen to anyone.. if one is not already there...

**Comment by loomchild** [comment]
In fact it was already there (see my above comments), I will highlight it a bit. Thanks for info!

**Comment by matanox** [comment]
Oh, sorry!
Thanks again for maintaining this great code base!

**Comment by loomchild** [comment]
No worries, I wasn't blaming you:)

I improved the error message in the exception, which should also propagate to console error.
