### ISSUE TITLE
Cannot use LanguageTool's SRX file

### ISSUE THREAD

**Issue by handhikadj** [loomchild/segment#19]
I've tried on a file with `bin/segment -s ~/Documents/languagetoolorg-srx.srx -i ~/Documents/example.txt -o ~/Documents/example.out.txt` the output file is still what it is

**Comment by janissl** [comment]
I think the problem lies in the missing -l (the language) argument in your command. The segmenter must "know" which language rules to apply.

**Comment by handhikadj** [comment]
thank you so much. that works
