### ISSUE TITLE
Add the paper to the readme

### ISSUE THREAD

**Issue by milekpl** [loomchild/segment#23]
I guess academic users might want to cite our work on this?

Miłkowski, M., & Lipski, J. (2011). Using SRX Standard for Sentence Segmentation. In Z. Vetulani (Ed.), Human Language Technology. Challenges for Computer Science and Linguistics (pp. 172–182). Berlin, Heidelberg: Springer Berlin Heidelberg. doi: [10.1007/978-3-642-20095-3_16](https://doi.org/10.1007/978-3-642-20095-3_16)

I'd add this to the readme ;)

**Comment by loomchild** [comment]
Done, thanks.
